[package]
name = "api-rest"
edition.workspace = true
version.workspace = true

[dependencies]
entity.workspace = true
repository.workspace = true
config.workspace = true
import.workspace = true
axum = "0.8"
tower = "0.5"
tower-http = { version = "0.6", features = ["compression-gzip", "decompression-gzip", "trace"] }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
base64 = "0.22"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
